$version = (dotnet gitversion /output json /format "{Major}.{Minor}.{Patch}.{ShortSha}.{PreReleaseLabel}")

$cs = @"
// auto-generated by version.ps1 — do not edit
namespace skyplan {
    internal static class VersionInfo {
        public const string Version = "$version";
    }
}
"@
Set-Content -Path "$PSScriptRoot\skyplan\VersionInfo.cs" -Value $cs -Encoding UTF8
Write-Output $version
