$version = (dotnet gitversion /output json /format "{Major}.{Minor}.{Patch}.{ShortSha}.{PreReleaseLabel}")

$cs = @"
// auto-generated by version.ps1 — do not edit
namespace skyplan {
    internal static class VersionInfo {
        public const string Version = "$version";
    }
}
"@
Set-Content -Path "$PSScriptRoot\skyplan\VersionInfo.cs" -Value $cs -Encoding UTF8

$layersPath = "$PSScriptRoot\SkyPlanUI\src\layers.json"
$layers = Get-Content $layersPath -Raw | ConvertFrom-Json
$layers.version = $version
$layers | ConvertTo-Json -Depth 10 | Set-Content $layersPath -Encoding UTF8

Write-Output $version
