<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<Version>0.1.0-beta</Version>
		<LangVersion>12.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<ManagedPath>$([System.Environment]::GetEnvironmentVariable('CSII_MANAGEDPATH', 'EnvironmentVariableTarget.User'))</ManagedPath>
	</PropertyGroup>

	<Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.props" />

	<ItemGroup>
		<ProjectReference Include="..\Skyplan.Models\Skyplan.Models.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="UnityEngine.CoreModule">
			<Private>false</Private>
		</Reference>
		<Reference Include="Unity.Mathematics">
			<Private>false</Private>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<Private>false</Private>
		</Reference>
	</ItemGroup>
	<PropertyGroup>
		<LangVersion>12.0</LangVersion>
	</PropertyGroup>
</Project>
